### ISSUE TITLE
Decompose UserDashboard into smaller components with their own files

### ISSUE THREAD

**Issue by davidnmora** [Mitch4sho/github-user-search-app#3]
eg DashboardHeader

**Comment by Mitch4sho** [comment]
Hi, @davidnmora , would you mind reviewing please if you had time. If not, that is completely fine :). 
I did what you said about decomposing the components in the user dashboard. Also, I put styled components into the mix and rid of vanilla styling. please let me know if it's up to standard :) I appreciate any help you can provide.
