### ISSUE TITLE
Replace the hard-coded Doge JSX with a passed-in hard-coded Doge user object

### ISSUE THREAD

**Issue by davidnmora** [Mitch4sho/github-user-search-app#5]
UserDashboard shouldn't have to worry about a special case. It should just render user objects.

This also removes the need for the `initialLoad` state.

**Comment by Mitch4sho** [comment]
How do I link this issue to a branch that I'm working on @davidnmora ?  is this a possibility?

**Comment by Mitch4sho** [comment]
I have resloved this :)
